---
- name: Install LAMP Stack on Ubuntu
  hosts: webserver
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: no

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install PHP and required modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

 


   
